bestlkh/ice-MC2

public/app/js/chatroomPlus.js

Fixed dragbar disappear issue.
The problem was that class `.active` was not removed for `#dragbar` on mouseup events.

Fixed dragbar disappear  issue

---

AdminView/constants.js
app.js
chatNsp.js
message.js
public/app/controllers/chatRoomController.js
public/app/controllers/loginController.js
public/app/js/ui.js
public/app/views/chatRoom.html

image upload and delete messages

---

public/app/controllers/chatRoomController.js

Image upload in chat now restricted to 1080p.

Added image resize function.

---

message.js
public/app/controllers/loginController.js
public/app/views/login.html

* Removed initial input box from login screen (type set to hidden)
* Changed initial generation rule for both client-side and server-side.
Now your initial will be one of the two:
If your name does not contain space, for example: `jack`.
Your initial will then be `JA`.
If your name does contain space, for example: `Jun Zheng`, `First Middle Last`
Your initial will then be `JZ`, `FL`

Removed initial input box, changed initial generation rule.

---

public/app/js/ui.js

Change getBubbleMenuButtonMarkup definition to include title and update corresponding chat bubble button instances

Add tooltip when hovering over chat options

---

public/app/styles/chatroom/chat.less
public/app/views/chatRoom.html

- scroll bar for chat conversation is no longer hidden behind the footer
- decrease size of the list displaying users in chat 
- made chat list sticky
- refactoring & overall improvements on layering and responsiveness

Improvement to Chat UX

---

public/app/controllers/loginController.js
public/app/styles/chatroom/chat.less
public/app/views/login.html

- fix console errors appearing in login that tried to access properties of undefined objects
- transparency of chat participant items increased to match the list

General Cleanup

---

public/app/controllers/loginController.js
public/app/styles/chatroom/direct-chat.less

Add random avatar function on login. Centered initials in chatroom avatar.

Add Random Avatar Function

---

public/app/styles/chatroom/chat.less

Remove debugging background colour

---

public/app/controllers/chatRoomController.js
public/app/views/chatroom/chat-text-menu.html

* Added edit feature for all text messages, it will simply put back to text area.
* Fixed a bug where when you switch to latex multiline editor, the latest message gets covered by it.
* Fixed a bug where on `message multi` event, `#dcs` does not scroll properly.

Added edit feature for ALL messages, fixed some minor bugs

---

public/app/js/ui.js

- duplicate image upload button from the chat options bubble menu should no longer be there

Remove duplicate image upload button under the menu

---

public/app/views/chatroom/chat-text-content.html
public/app/views/chatroom/chat-text-inner.html

Added message render template.
Now if you do:
```
<div ng-include="'/app/views/chatroom/chat-text-content.html'"></div>
```
Message should be automatically rendered, make sure when including the template, it has access to `message` variable, which should be a `Message` instance.

Added message render template.

---

public/app/js/ice/ui.js
public/app/styles/ice/global.less
public/app/styles/ice/iframe.less
public/app/styles/ice/misc.less
public/app/views/ICE/css/method-draw.css
public/app/views/ICE/ice.html
public/app/views/ICE/src/method-draw.js
public/app/views/chatroom/chat-img.html

Firefox UX Fixes

---

app.js
public/app/controllers/loginController.js
public/app/css/style.css
public/app/styles/chatroom/global.less
public/app/styles/chatroom/login.less
public/app/styles/chatroom/phone.less
public/app/styles/chatroom/tablet.less
public/app/styles/latex-preview/main.css
public/app/views/login.html
public/index.html

Responsive page, UX improvements and gradual deletion of legacy styles.

Refactor Chat Login to be Responsive

---

.eslintrc.json
package-lock.json
package.json

Basic configuration for the ESLint file. Some rules that were added based on the init file questionnaire.
- 4 spaces
- semicolon required after end of JavaScript statements
There are also options to change/disable any default style checks. Most IDE's have plugin support to show these style issues dynamically in the editor and automatically fix them. Otherwise check documentation for the command line interface alternatives.

Generate ESLint File

---

public/index.html
public/landing/index.html
public/register/index.html

- Update references to the minified version of angular.js

Optimization- Minify Angular.js

---

public/app/js/ui.js
public/app/styles/chatroom/chat-message.less
public/app/styles/chatroom/global.less
public/app/styles/chatroom/login.less
public/app/views/chatRoom.html
public/app/views/chatroom/chat-info.html
public/app/views/login.html
public/index.html

- The student view
- The admin view
- replaced orange background with a darker colour

Improve Message Contrast

---

public/app/js/chatroomPlus.js
public/app/js/src/recognition/BracketSymbol.js
public/app/js/src/recognition/RecognitionTool.js
public/app/styles/chatroom/global.less

* Made distance between toggle and chatroom shorter.
* Some code formatting, delete unused blank lines, added necessary blank lines.

Format code a bit. Made distance between toggle and chatroom shorter.

---

public/app/js/chatroomPlus.js
public/app/js/src/recognition/BracketSymbol.js
public/app/js/src/recognition/RecognitionTool.js
public/app/styles/chatroom/global.less
public/app/views/ICE/src/svgcanvas.js

Uncommented the rotation code. 
Note: The blue snap points that appear when selecting the image are not adjusted.

Enable rotation.

---

public/app/controllers/loginController.js

This should fix normal chat messages being on the wrong side

Fixed: Normal chat own username not being set

---

public/app/styles/chatroom/global.less
public/app/styles/latex-preview/global.less

Fix issue where the latex preview would take too much space on mid size screens and obscure editor menu items.

Update to dynamic sizing.

---

AdminView/index.js

Fixed images in messages in export/adminview
